# Generated by Django 4.2.7 on 2024-03-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('product', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='contactmessage',
        #     name='idid',
        # ),
        # migrations.RemoveField(
        #     model_name='post',
        #     name='idid',
        # ),
        # migrations.AddField(
        #     model_name='contactmessage',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='post',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
    ]
