# Generated by Django 4.2.5 on 2024 h-09-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('idid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idid')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=5000)),
            ],
        ),
    ]
