# Generated by Django 4.2.7 on 2024-03-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='contactmessage',
        #     name='idid',
        # ),
        # migrations.AddField(
        #     model_name='contactmessage',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
    ]
